spring:
  datasource:
    url: jdbc:mysql://localhost:3306/responsedata
    username: root
    password: Parametric@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8585
